#!/bin/sh
### BEGIN INIT INFO
# Provides:          cktunnel
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Check for tunnel request
# Description:       Check for request to establish tunnel for remote access
### END INIT INFO

tstamp () {
    date --iso-8601=seconds
}

set -e

SCRIPT="/opt/cktunnel/cktunnel"
NAME=`basename "$SCRIPT"`
PIDFILE=/var/run/$NAME.pid
RUNASUSER=placeholder
LOGDIR=/var/opt/$NAME/log

# Check for daemon presence
[ -x "$SCRIPT" ] || exit 4  # program unknown


# Get lsb functions
. /lib/lsb/init-functions

# XXX "log" output from script not handled yet

case "$1" in
  start)
    log_begin_msg "Starting $NAME..."
    if [ -e "$LOGDIR/$NAME.log" ]
    then
        mv "$LOGDIR/$NAME.log" "$LOGDIR/$NAME.`date '+%Y%m%d-%H%M%S'`.log"
    fi
    start-stop-daemon --start --chuid $RUNASUSER --oknodo --background \
        --startas "$SCRIPT" --chdir "`dirname $SCRIPT`" --no-close \
        --verbose --pidfile "$PIDFILE" --make-pidfile --remove-pidfile \
        >> $LOGDIR/$NAME.log 2>&1
    log_end_msg $?
    ;;
  stop)
    log_begin_msg "Stopping $NAME..."
    echo `tstamp` "Stopping $NAME" >> "$LOGDIR/$NAME.log"
    start-stop-daemon --stop --quiet --oknodo \
        --pidfile $PIDFILE --remove-pidfile
    log_end_msg $?
    ;;
  status)
    start-stop-daemon --status --pidfile $PIDFILE --remove-pidfile
    ;;
  restart|reload|force-reload) 
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    log_success_msg "Usage: /etc/init.d/$NAME {start|stop|status|restart|reload|force-reload}"
    exit 1
esac
